apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappclient
  template:
    metadata:
      labels:
        app: webappclient
    spec:
      containers:
        - name: webappclient
          image: petartotev/webappclientimage:latest
---
apiVersion: v1
kind: Service
metadata:
  name: webappclient-nodeport-service
spec:
  type: NodePort
  selector:
    app: webappclient
  ports:
    - name: webappclient
      protocol: TCP
      port: 80
      targetPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webappclient-clusterip-service
# spec:
#   type: ClusterIP
#   selector:
#     app: webappclient
#   ports:
#   - name: webappclient
#     protocol: TCP
#     port: 80
#     targetPort: 80

########################################

# kubectl apply -f webappclient-deployment.yaml

# kubectl get all
# kubectl get services => get nodeport port 3xxxx
# kubectl get deployments
# kubectl get pods

# kubectl delete service webappclient-nodeport-service
# kubectl delete service webappclient-clusterip-service
# kubectl delete deployment webappclient-deployment